title: warrick.io
email: kevinjwarrick@gmail.com
description: >-
baseurl: ""
url: "https://blog.warrick.io"
twitter_username: kevinjwarrick
github_username:  kwarrick

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
